# Generated by Django 5.1.3 on 2025-02-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_initial'),
        ('user', '0006_remove_user_roles_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Menü', 'verbose_name_plural': 'Menüler'},
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menu', verbose_name='Üst Menü'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='menus', to='user.role', verbose_name='Roller'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL Adı'),
        ),
    ]
