# Generated by Django 5.1.3 on 2025-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_options_menu_is_active_menu_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['level', 'order', 'title'], 'verbose_name': 'Menü', 'verbose_name_plural': 'Menüler'},
        ),
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(default=0, editable=False, verbose_name='Seviye'),
        ),
    ]
