# Generated by Django 5.1.3 on 2025-02-13 13:35

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Yönetici'), ('user', 'Kullanıcı'), ('editor', 'Editör'), ('moderator', 'Moderatör')], max_length=20, unique=True, verbose_name='Rol Adı')),
                ('description', models.TextField(blank=True, verbose_name='Rol Açıklaması')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta Adresi')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon Numarası')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil Resmi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış Kullanıcı')),
                ('groups', models.ManyToManyField(blank=True, help_text='Kullanıcının ait olduğu gruplar', related_name='user_groups', to='auth.group', verbose_name='Gruplar')),
                ('roles', models.ManyToManyField(related_name='users', to='user.role', verbose_name='Kullanıcı Rolleri')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Kullanıcının özel izinleri', related_name='user_permissions_set', to='auth.permission', verbose_name='Kullanıcı izinleri')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
