# Generated by Django 5.1.3 on 2025-02-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roller'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('owner', 'Yönetici'), ('personel', 'Personel'), ('attendant', 'Görevli')], max_length=20, unique=True, verbose_name='Rol'),
        ),
    ]
