# Generated by Django 5.1.3 on 2025-02-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_role_options_remove_role_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='user.role', verbose_name='Kullanıcı Rolü'),
        ),
    ]
