# Generated by Django 5.1.3 on 2025-02-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_roles_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Maksimum boyut 2MB ve boyutlar 200x200 piksel olmalıdır', null=True, upload_to='profile_pics/', verbose_name='Profil Resmi'),
        ),
    ]
